# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Tidy Recordings
version: "1.0"
slug: tidy-recordings
description: Auto compress, remove silence, and organize the Assist Pipeline recordings
url: "https://github.com/Erudition/hass-pandora-addon/tree/main/tidy-recordings"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  processed_recording_folder: "recordings"
  output_segment_size: 3600
  max_folder_size_megabytes: 100000
  max_overall_disk_usage_percent: 90
schema:
  processed_recording_folder: match(^((/[a-zA-Z0-9-_]+)+|/)$)
  output_segment_size: int
  max_folder_size_megabytes: int(100,10000000)
  max_overall_disk_usage_percent: int(50,99)

#image: "ghcr.io/home-assistant/{arch}-addon-example"
