# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pandora HASSOS
version: "0.5"
slug: pandora
description: Pianobar on HASSOS
url: "https://github.com/Erudition/hass-pandora-addon/tree/main/pandora"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  username: null
  password: null
  autostart_station: "None"
schema:
  username: email
  password: password
  autostart_station: str
#image: "ghcr.io/home-assistant/{arch}-addon-example"
audio: true
