# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Pandora HASSOS
version: "0.3"
slug: pandora
description: Pianobar on HASSOS
url: "https://github.com/Erudition/hass-pandora-addon/tree/main/pandora"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
  username: null
  password: null
  autostart_station: null
schema:
  message: "str?"
  username: str
  password: str
  autostart_station: int?
#image: "ghcr.io/home-assistant/{arch}-addon-example"
audio: true
